### ISSUE TITLE
User wants to search for address

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#122] opened 2017-08-11 20:14 UTC
I want to be able to search for an address to find a relevant project

**Comment by CeciliaCY** [comment] 2017-08-11 21:16
As an example -  there is a search function in Zoning Index Map page - http://www1.nyc.gov/site/planning/zoning/index-map.page. You can search for a location using BBL (Borough, Block, Lot), BIN (Building Identification Number) or Address. It uses Geoclient API from NYC Developer Portal.

**Comment by chriswhong** [comment] 2017-08-11 21:49
Recommend using a consumer-ready geocoder with autocomplete suggestions such as Mapzen's or Mapbox's if we want to do address lookup.  

I support BIN and BBL lookup in general, but wonder if these are relevant to users of the community portal.  Do we have any stats on how much these types of lookups occur on the existing pages that use them?

 I think requiring the user to enter a borough prior to address search is a poor user experience for quickly locating an address on the map.

**Comment by chriswhong** [comment] 2017-08-14 15:02
Duplicate of #133

**Closed by chriswhong** 2017-08-14 15:02 UTC
Labels: feedback
